/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LifecycleRouteImport } from './routes/lifecycle'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicV1HealthRouteImport } from './routes/api/public/v1/health'

const LifecycleRoute = LifecycleRouteImport.update({
  id: '/lifecycle',
  path: '/lifecycle',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1HealthRoute = ApiPublicV1HealthRouteImport.update({
  id: '/api/public/v1/health',
  path: '/api/public/v1/health',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lifecycle': typeof LifecycleRoute
  '/api/public/v1/health': typeof ApiPublicV1HealthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lifecycle': typeof LifecycleRoute
  '/api/public/v1/health': typeof ApiPublicV1HealthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lifecycle': typeof LifecycleRoute
  '/api/public/v1/health': typeof ApiPublicV1HealthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/lifecycle' | '/api/public/v1/health'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lifecycle' | '/api/public/v1/health'
  id: '__root__' | '/' | '/lifecycle' | '/api/public/v1/health'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LifecycleRoute: typeof LifecycleRoute
  ApiPublicV1HealthRoute: typeof ApiPublicV1HealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/lifecycle': {
      id: '/lifecycle'
      path: '/lifecycle'
      fullPath: '/lifecycle'
      preLoaderRoute: typeof LifecycleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/health': {
      id: '/api/public/v1/health'
      path: '/api/public/v1/health'
      fullPath: '/api/public/v1/health'
      preLoaderRoute: typeof ApiPublicV1HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LifecycleRoute: LifecycleRoute,
  ApiPublicV1HealthRoute: ApiPublicV1HealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
